name: Build and Deploy

on:
  push:
    branches:
      - AmigoSecreto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create docs directory if not exists
      run: mkdir -p docs

    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1.0.13
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
